name: modudi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # For localization

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod: ^2.6.1
  go_router: ^14.0.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.3
  logging: ^1.2.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  epub_view: ^3.2.0
  url_launcher: ^6.1.12
  flutter_pdfview: ^1.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.3
  youtube_player_iframe: ^4.0.4
  timeline_tile: ^2.0.0
  
  # Firebase packages
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  firebase_analytics: ^10.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  
  # Enable generation of localized strings from ARB files
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  
