name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of what you want to happen
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem and how this feature would solve it
      placeholder: I'm always frustrated when...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (app doesn't work without it)
        - High (significantly improves usability)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request here.
